name: Deploy Flutter web app to Cloudflare Pages

on:
  push:
    branches: [ "cloudflare-publish" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
    Deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy Flutter web app to Cloudflare Pages
          uses: senthilnasa/flutter-cloudflare-pages@v2
          with:
            # Which web renderer to be used, default is auto
            webRenderer: # optional, default is auto

            # The directory where the project is (default .)
            workingDir: # optional, default is .

            # base href (if applicable)
            baseHref: # optional, default is /

            # Custom args like: --dart-define="simple=example"
            customArgs: # optional, default is 

            # The Cloudflare Project Name
            cfProjectName: Timeline

            # The Cloudflare API Token
            cfApiToken: nE-oVS_YgFRK8IyUAidKkv1XesYXuT_ksE46l6uw

            # The Cloudflare Account ID
            cfAccountId: dc1b55f712dbc6702471c2c53d5f1b60
